### ISSUE TITLE
AsyncPlayerChatEvent not communicating -> Plugin

### ISSUE THREAD

**Issue by SimpleWayx** [Hadimhz/WelcomeBack#1]
While using the [Chatformater ](https://www.spigotmc.org/resources/%EF%B8%8F-chatformatter-%E2%9C%94%EF%B8%8F-beautify-your-chat-with-hovers-clickable-messages-and-more.102212/)+ Paper addon.

[11:45:03 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatFormatter v1.0.7
java.lang.IllegalStateException: AsyncChatEvent may only be triggered asynchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[paper-1.20.1.jar:git-Paper-195]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-195]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.eternalcode.formatter.paper.ChatPaperPreparatory.prepare(ChatPaperPreparatory.java:50) ~[ChatFormatter-PaperSupport.v1.0.7.jar:?]
        at com.eternalcode.formatter.preparatory.ChatPreparatoryService.prepare(ChatPreparatoryService.java:24) ~[ChatFormatter.v1.0.7.jar:?]
        at com.eternalcode.formatter.ChatController.onChat(ChatController.java:135) ~[ChatFormatter.v1.0.7.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-195]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-195]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-195]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[paper-1.20.1.jar:git-Paper-195]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2459) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.chat(CraftPlayer.java:710) ~[paper-1.20.1.jar:git-Paper-195]
        at dev.hadimhz.welcome.command.Command.onCommand(Command.java:48) ~[WelcomeBack-1.0-SNAPSHOT-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:985) ~[paper-1.20.1.jar:git-Paper-195]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-195]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-195]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:45:03 INFO]: [Not Secure] [Server] hello

**Comment by Hadimhz** [comment]
The issue has been resolved. Download the latest version of [spigot](https://www.spigotmc.org/resources/welcomeback.112720/).

**Comment by SimpleWayx** [comment]
[05:53:49 WARN]: [WelcomeBack] Plugin WelcomeBack v1.0 generated an exception while executing task 1160
java.lang.IllegalStateException: AsyncPlayerChatEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[paper-1.20.1.jar:git-Paper-195]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-195]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[paper-1.20.1.jar:git-Paper-195]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[paper-1.20.1.jar:git-Paper-195]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2459) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.chat(CraftPlayer.java:710) ~[paper-1.20.1.jar:git-Paper-195]
        at dev.hadimhz.welcome.command.Command.lambda$onCommand$0(Command.java:52) ~[WelcomeBack-all.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-195]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-195]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
        The problem has arrised again event after updating it. For some reason it mentions 1.0v even though is version 1.1v

**Comment by Hadimhz** [comment]
@SimpleWayx was it solved or did i never fix it? I'm currently using the plugin on my server and it seems to not have any issues so i'm confused by this.

**Comment by Hadimhz** [comment]
Also, the plugin is currently on version 1.3 do you think you can update it?

**Comment by Hadimhz** [comment]
I fixed the Plugin WelcomeBack v1.0 generated an exception while executing task 1160 but it seems like it's impossible for a plugin to be able to send a chat on behalf of the player async. Which formatting even are you using?

**Comment by Hadimhz** [comment]
This issue is caused by certain chat formatting plugins and as far as I'm aware, i cannot do anything about it
